name: CI/CD

on:
  release:
    types: [published]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    name: Execute Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Test
        run: ./unit-test.sh
